name:                hskit
version:             0.1.0.0
github:              "isovector/hskit"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2019 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/hskit#readme>

dependencies:
- base >= 4.7 && < 5
- async
- gi-gdk
- gi-gio
- gi-gtk
- gi-gtk-hs
- gi-webkit2 >=4.0.6 && <4.1
- gi-webkit2webextension
- haskell-gi-base
- polysemy
- polysemy-plugin
- polysemy-zoo
- text
- containers
- interpolatedstring-qq2
- bytestring
- network
- binary

library:
  source-dirs: src

ghc-options:
  - -fplugin=Polysemy.Plugin
  - -Wall

verbatim: |
  foreign-library hskit-ext
    type:                native-shared
    lib-version-info:    0:0:3
    hs-source-dirs:         extension

    if os(Windows)
      options: standalone

    pkgconfig-depends: webkit2gtk-web-extension-4.0

    ghc-options: -Wall -threaded

    other-modules:       SimpleExtension
    build-depends:       base >=4.7 && <5,
                         haskell-gi-base,
                         hskit,
                         gi-webkit2webextension == 4.0.*,
                         text >= 1.0
    c-sources:           extension/SimpleExtensionInit.c
    default-language:    Haskell2010

default-extensions:
  - DataKinds
  - DeriveFunctor
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - UnicodeSyntax
  - OverloadedLabels

executables:
  hskit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hskit

tests:
  hskit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hskit
