resolver: lts-13.0

packages:
- .

extra-deps:
- polysemy-0.5.0.0
- polysemy-plugin-0.2.1.0
- polysemy-zoo-0.3.0.0
- bifunctors-5.5.4
- th-lift-0.8.0.1
- interpolatedstring-qq2-0.1.0.0
- th-abstraction-0.3.1.0
- haskell-gi-0.22.4
- haskell-gi-base-0.22.2
- gi-atk-2.0.19
- gi-cairo-1.0.21
- gi-gdk-3.0.20
- gi-gdkpixbuf-2.0.21
- gi-gio-2.0.23
- gi-glib-2.0.21
- gi-gobject-2.0.20
- gi-gtk-3.0.30
- gi-gtk-hs-0.3.7.0
- gi-javascriptcore-4.0.19
- gi-pango-1.0.20
- gi-soup-2.4.20
- gi-webkit2-4.0.23
- gi-webkit2webextension-4.0.22
- first-class-families-0.5.0.0
- unagi-chan-0.4.1.0

flags:
  polysemy:
    error-messages: False

